### ISSUE TITLE
Add a Debug.log in the template update function

### ISSUE THREAD

**Issue by avh4** [elmbridge/curriculum#95]
It might be nice to have the `update` function in the starting point do:

``` elm
case Debug.log "update" msg of
   ...
```

so that when students add a new message they can see it happen in the javascript console.

**Comment by raorao** [comment]
I would rather not add code that makes the skeleton app look different from a production elm app. Some differences are necessary (e.g. using `beginnerProgram` vs `program`), but I'd like to limit those as much as we can. 

IMO, skeletons are a necessary evil, since they are documents often consumed outside the context of a curriculum. Students often have a hard time telling what's necessary vs what's a useful trick the author put in for learning purposes. Consequently, I try to include as little as possible in my skeletons.

**Comment by raorao** [comment]
I'm closing this, but feel free to re-open if you feel strongly @avh4
